services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - "28080:8080"
    environment:
      - PORT=
      - TZ=Asia/Shanghai
      - PROXY=
      - OPENAI_EMAIL=
      - OPENAI_PASSWORD=
      - CONTINUE_SIGNAL=
      - ENABLE_HISTORY=
      - IMITATE_ACCESS_TOKEN=
      - ARKOSE_TOKEN_URL=http://arkoselabs_token_api.get:8081/token/
    volumes:
      - ./chat.openai.com.har:/app/chat.openai.com.har
    restart: unless-stopped
    extra_hosts:
      -  host.docker.internal:host-gateway
    depends_on:
      - arkoselabs_token_api.get
  arkoselabs_token_api.get:
    container_name: arkoselabs_token_api.get
    image: 24802117/arkoselabs_token_api.get:latest
    environment:
      db: false
#      http_proxy: http://10.18.96.99:7890
    volumes:
      - type: bind
        source: ./chat.openai.com.har
        target: /home/app/chat.openai.com.har
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    ports:
      - "28081:8080"